---
- name: Launch sonarqube container
  docker_container:
    name: sonarqube
    image: "sonarqube:{{ sonarqube_version | default('latest') }}"
    restart_policy: always
    pull: "{{ docker_pull_image | default('no') }}"
    ports:
      - "{{ sonarqube_port | default('9000') }}:9000"
#    links:
#      - postgresql:db
    env:
      SONARQUBE_JDBC_USERNAME: "{{ postgresql_user }}"
      SONARQUBE_JDBC_PASSWORD: "{{ postgresql_password }}"
#      SONARQUBE_JDBC_URL: "jdbc:postgresql://db/{{ postgresql_database }}"
      SONARQUBE_JDBC_URL: "{{ jdbc_url }}"
    volumes:
      - sonarqube-conf:/opt/sonarqube/conf
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-extensions:/opt/sonarqube/extensions
      - sonarqube-bundled-plugins:/opt/sonarqube/lib/bundled-plugins
  tags: sonarqube
